### ISSUE TITLE
The number of issues and pull requests are wrong

### ISSUE THREAD

**Issue by GustavoVale** [xai/filter-github-projects#3]
The numbers of pull requests and issues provided by the tool are a little different from the result we see looking the interface. However the difference is not so big, in the cases I checked, and I don't think that it is problem for our search.

**Comment by xai** [comment]
I just changed get_num_entries(), making it a little less error prone. Can you check again please?

**Comment by GustavoVale** [comment]
The pull seems nice. I wanted to do use 'links' like you did, but I found a solution in the another way first. 

Tomorrow I check with the values I wrote in a paper in the office.

**Comment by GustavoVale** [comment]
It works.
